---
title: "EDLD 653 Lab 2"
author: "Raleigh Goodwin"
date: "4/14/2021"
output: html_document
---

```{r}
library(tidyverse)
library(repurrrsive)
library(httr)
library(purrr)
library(magrittr)

```

# A

```{r}
file <- "https://github.com/datalorax/esvis/raw/master/data/benchmarks.rda"
load(url(file))
head(benchmarks)

benchmarks <- benchmarks %>%
	as_tibble() %>%
	mutate(wave = case_when(season == "Fall" ~ 0,
	                        season == "Winter" ~ 1,
	                        TRUE ~ 2))
```

# 1 

```{r}
by_sid = split(benchmarks, benchmarks$sid)
mods = map(by_sid, ~lm(math ~ wave, data = .x))
#str(mods)

```

# 2 

```{r}
coefs <- map(mods, coef)
slopes <- map_dbl(coefs, 2)
relation <- tibble(wave = names(slopes),
                   slope = slopes)
ggplot(relation, aes(slope)) +
    geom_histogram(fill = "cornflowerblue",
                   color = "white") +
  theme_minimal()+
  geom_vline(xintercept = mean(slopes, na.rm = T), linetype = "dashed")+
  geom_text(aes(x=mean(slopes, na.rm = T), label="mean of slopes", y=145), colour="grey", text=element_text(size=3), fontface = "italic")
```


# B

# 1 

```{r}
# sw_films %>% 
#   str()

swf <- 1:length(sw_films)
films <- data.frame(matrix(ncol=2,nrow=length(sw_films), dimnames=list(NULL, c("title", "characters"))))

for(i in swf){
  films$title[i] <- sw_films[[i]]$title
  films$characters[i] <- as.list(sw_films[[i]]$characters) %>% 
    length()
}

#map function for this question
film.titles = map(sw_films, "title")
film.chars = map(sw_films, "characters") %>%  
 map_dbl(length)

tibble(Film = film.titles, No._Chars = film.chars) %>% 
  knitr::kable()

```

# 2 

```{r}
# sw_species %>% 
#   length()

# sw_species[[2]]$hair_colors
# sw_species[[2]]$name

spec <- 1:length(sw_species)
hair <- data.frame(matrix(ncol=2,nrow=length(sw_species), dimnames=list(NULL, c("name", "color"))))


for(i in spec){
  hair$name[i] <- sw_species[[i]]$name
  hair$color[i] <- sw_species[[i]]$hair_colors
}

hair %>%
  filter(color != "n/a" & color != "none")


#map names and hair color across lists
map_chr(sw_species, ~.x$hair_colors)


sw_species %>%
  map_dfr(., extract, c("hair_colors", "name")) %>% 
  filter(!hair_colors %in% c("n/a", "unknown", "none")) %>%  #remove NA, none and unknown values
  knitr::kable()


```


# C

# 1

```{r}
# GET("https://pokeapi.co/api/v2/ability/1") %>%
# 	content("parsed") 
# 
# vctr <- 1:5
# urls <- rep(NA, length(vctr))
# 
# for(i in vctr){
#   urls[i] <- paste0("https://pokeapi.co/api/v2/ability/",i)
# }
# 
# urlsm <- map(vctr, function(x) paste0("https://pokeapi.co/api/v2/ability/",x))
# 
# map(urlsm, function(x) GET(urlsm) %>% content("parsed"))
# 
# urlsm[1]

pokemon5 <- map(paste0("https://pokeapi.co/api/v2/ability/",1:5), ~GET(.x))
str(pokemon5)

pokemon5_abs <- map(pokemon5, ~content(.x,"parsed"))
```

# 2

```{r}
pokemon5_abs %>% 
   map_dfr(., extract, c("name"))

str(pokemon5_abs)

pokemon5_abs %>% 
   map(., extract, c("pokemon")) %>% 
   map(., ~length(.x$pokemon))

Names <- map_chr(pokemon5_abs, "name")
Count <- map_int(pokemon5_abs, ~length(.x$pokemon))

# cbind(pokename, pokenum)

pokedf <- tibble(Names, Count)
pokedf

```

# 3 (bonus) 
```{r}
name.List = map(list1$results, "name") %>% 
  unlist() %>% 
  data_frame()

#This introduces a new column
name.List %>% 
  rownames_to_column( var = "var_name")
```

